version: "2"

services:
    shakespeer:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        # App files and config
        - ./config/uwsgi.ini:/app/uwsgi.ini:ro
        - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
        - ./app/main.py:/app/main.py:ro
        - ./templates/:/app/templates/:ro
        - ./data/:/app/data/:rw
        # Library
        - .:/usr/local/lib/python3.6/site-packages/shakespeer:ro
        # Linter and tests
        - .flake8:/.flake8:ro
        - ./tests/:/app/tests/:ro
      ports:
        - 8080:8080
